import 'package:frontend/models/address.dart';

enum BookingStatus { booked, cancelled, inProgress, completed }

class Booking {
  const Booking({
    this.id, //generated by DB
    required this.userID,
    required this.name,
    required this.surname,
    required this.pickUpLocation,
    required this.dropOffLocation,
    required this.bookingTime,
    required this.bookingStatus,
  });

  final int? id;
  final int userID;
  final String name;
  final String surname;
  final Address pickUpLocation;
  final Address dropOffLocation;
  final DateTime bookingTime;
  final BookingStatus bookingStatus;
}
