FROM nginx:latest

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY default.conf /etc/nginx/conf.d/default.conf

COPY entrypoint.sh entrypoint.sh
RUN chmod +x ./entrypoint.sh

RUN mkdir -p /etc/nginx/ssl

EXPOSE 443

WORKDIR /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
